### ISSUE TITLE
User and Organization Management 

### ISSUE THREAD

**Issue by KericeRich** [bcgov/lcfs#127]
# Dependencies

## Epic

- [ ] bcgov/lcfs/issues/98
- [ ] bcgov/lcfs/issues/99
- [ ] bcgov/lcfs/issues/105
- [x] bcgov/lcfs/issues/130
- [x] bcgov/lcfs/issues/131
- [ ] bcgov/lcfs/issues/133
- [ ] bcgov/lcfs/issues/139
- [ ] bcgov/lcfs/issues/145
- [x] bcgov/lcfs/issues/154
- [ ] bcgov/lcfs/issues/155
- [ ] bcgov/lcfs/issues/157
- [x] bcgov/lcfs/issues/160
- [x] bcgov/lcfs/issues/161
- [x] bcgov/lcfs/issues/162
- [x] bcgov/lcfs/issues/165
- [x] bcgov/lcfs/issues/166
- [ ] bcgov/lcfs/issues/168
- [ ] bcgov/lcfs/issues/173
- [x] bcgov/lcfs/issues/174
- [x] bcgov/lcfs/issues/175
- [x] bcgov/lcfs/issues/176
- [x] bcgov/lcfs/issues/178
- [ ] bcgov/lcfs/issues/184
- [x] bcgov/lcfs/issues/186
- [x] bcgov/lcfs/issues/187
- [ ] bcgov/lcfs/issues/191
- [ ] bcgov/lcfs/issues/194
- [ ] bcgov/lcfs/issues/196
- [x] bcgov/lcfs/issues/207
- [x] bcgov/lcfs/issues/208
- [x] bcgov/lcfs/issues/211
