### ISSUE TITLE
LCFS - Progress tracking breadcrumb on new transfers page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#213]
**Description:**

- Add a progress tracking breadcrumb to the new transfer page.
- Material UI
- Statuses to include in breadcrumb for BCeID users: Draft > Sent > Submitted > Recorded
- Draft is selected within the breadcrumb

Note: there will be some additional statuses included in this breadcrumb for IDIR users only and/or if the transfer is a certain status (e.g., refused, rescinded, declined)

**Wireframe:** https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/164975114/simulate/no-panels

**Purpose and benefit to user:**
Enables the user to track the progress of a transfer and understand where it currently resides in terms of workflow / processing / completion

**Acceptance Criteria:**

- [x] Given I am a BCeID, When I am on the transfers page, then the breadcrumb should show
- [x] the breadcrumb should show 4 steps ( draft, sent, submitted, recorded ).
- [ ] when a step is complete, its corresponding breadcrumb step should show the checkmark ui

**Development Checklist:**
- [ ] In the breadcrumb component, check the current step to show appropriate icons/ui

**Notes:**
- [ ] MUI component

**Comment by justin-lepitzki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/lcfs/213?planning-poker) with Zenhub @AlexZorkin @hamed-valiollahi @jig-patel @kevin-hashimoto @prv-proton

**Comment by justin-lepitzki** [comment]
Note for testing: The default view for a newly created transfer should be that the progress bar is completely greyed out. Progress will then begin tracking when the user saves a draft or sends the transfer to the other organization (i.e., at a point when the transaction is created and assigned an ID #).

**Comment by hamed-valiollahi** [comment]
@justin-lepitzki Thank you for adding the testing notes. Since this feature is not yet fully functional and requires backend implementation for complete testing, I've included a few screenshots for you to preview how it will appear.

<img width="733" alt="Screen Shot 2024-01-30 at 1 32 30 PM" src="https://github.com/bcgov/lcfs/assets/2143103/8e973792-c9b9-48d6-809b-bef37d3d21c7">
<img width="733" alt="Screen Shot 2024-01-30 at 1 32 37 PM" src="https://github.com/bcgov/lcfs/assets/2143103/533c65e3-0b31-4541-8366-8bd3273073e0">
<img width="733" alt="Screen Shot 2024-01-30 at 1 32 46 PM" src="https://github.com/bcgov/lcfs/assets/2143103/ad2082ea-bf16-40ac-baf5-0def88e0d5fe">
<img width="733" alt="Screen Shot 2024-01-30 at 1 32 53 PM" src="https://github.com/bcgov/lcfs/assets/2143103/b9e3878b-cbd3-471f-8185-88fbd8b6960e">

**Comment by Grulin** [comment]
Requires BCeID user access to test.
